### ISSUE TITLE
It doesn't seem to detect

### ISSUE THREAD

**Issue by ginodecock** [valentinbarral/esp32s2-ftm-tag#2]
There doesn't seem to be a scan of an ftm ap.
The result:
--- idf_monitor on com3 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x504
load:0x4004c000,len:0x824
load:0x40050000,len:0x2384
entry 0x4004c178

Is the project compatible with idf version 4.3?

Thanks,

**Comment by valentinbarral** [comment]
Yes, I've tested it with 4.3 and it should work. Check in the "SDK Configuration Editor" if the Wifi FTM is active, I think it's not by default.

**Comment by ginodecock** [comment]
Even enabling FTM in menuconfig I was not able to detect the Anchor. I also tested the default FTM sample to detect the Anchor but this also failed:
I (31435) ftm_station: sta scan doneftm_7CDFA1086050
I (31435) ftm_station: Requesting FTM session with Frm Count - 32, Burst Period - 200mSec (0: No Preference)
I (31465) ftm_station: FTM procedure with Peer(7c:df:a1:08:60:51) failed! (Status - 2)
ftm>

When changing in the Anchor sample the wifi_config by adding .ftm_responder = true the anchor worked with the default Espressif FTM sample

wifi_config_t wifi_config = {
        .ap = {
            .ssid = "",
            .ssid_len = 0,
            .max_connection = 4,
            .password = "",
            .authmode = WIFI_AUTH_WPA2_PSK,
            .channel = CURRENT_CHANNEL,
			.ftm_responder = true

        },
    };
I don't know what but something seems to be missing in your the tag project.

**Comment by ginodecock** [comment]
It seems that a burst_period of 1 results into an error. A burst period of 2 works.
wifi_ftm_initiator_cfg_t ftmi_cfg = {
        .frm_count = 16,
        .burst_period = 2,
    };
